// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zhiji.Contracts.Infrastructure;

namespace Zhiji.Contracts.Infrastructure.Migrations
{
    [DbContext(typeof(ContractContext))]
    partial class ContractContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zhiji.Contracts.Domain.Contracts.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId");

                    b.Property<DateTime?>("EndDate");

                    b.Property<DateTime>("StartDate");

                    b.Property<int?>("TemplateId")
                        .IsRequired();

                    b.Property<int>("TenementId");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Zhiji.Contracts.Domain.Templates.BillingMode", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("BillingModes");
                });

            modelBuilder.Entity("Zhiji.Contracts.Domain.Templates.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BillingModeId")
                        .IsRequired();

                    b.Property<int>("BillingPeriodMonth");

                    b.Property<int>("BillingPeriodOffsetMonth");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TimeZone")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BillingModeId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Zhiji.Contracts.Domain.Contracts.Contract", b =>
                {
                    b.HasOne("Zhiji.Contracts.Domain.Templates.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Zhiji.Contracts.Domain.Templates.Template", b =>
                {
                    b.HasOne("Zhiji.Contracts.Domain.Templates.BillingMode", "BillingMode")
                        .WithMany()
                        .HasForeignKey("BillingModeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Zhiji.Contracts.Domain.Templates.BillingDate", "BillingDate", b1 =>
                        {
                            b1.Property<int?>("TemplateId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Day");

                            b1.Property<int>("IntervalMonth");

                            b1.Property<int>("Month");

                            b1.ToTable("Templates");

                            b1.HasOne("Zhiji.Contracts.Domain.Templates.Template")
                                .WithOne("BillingDate")
                                .HasForeignKey("Zhiji.Contracts.Domain.Templates.BillingDate", "TemplateId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
