// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zhiji.Bills.Infrastructure;

namespace Zhiji.Bills.Infrastructure.Migrations
{
    [DbContext(typeof(BillContext))]
    partial class BillContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zhiji.Bills.Domain.Bills.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContractId");

                    b.Property<int>("CustomerId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("StatusId")
                        .IsRequired();

                    b.Property<int>("TemplateId");

                    b.Property<int>("TenementId");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Zhiji.Bills.Domain.Bills.BillStatus", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("BillStatuses");
                });

            modelBuilder.Entity("Zhiji.Bills.Domain.Bills.Bill", b =>
                {
                    b.HasOne("Zhiji.Bills.Domain.Bills.BillStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Zhiji.Bills.Domain.Bills.BillPeriod", "Period", b1 =>
                        {
                            b1.Property<int?>("BillId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTimeOffset>("End");

                            b1.Property<DateTimeOffset>("Start");

                            b1.ToTable("Bills");

                            b1.HasOne("Zhiji.Bills.Domain.Bills.Bill")
                                .WithOne("Period")
                                .HasForeignKey("Zhiji.Bills.Domain.Bills.BillPeriod", "BillId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
